apiVersion: apps/v1
kind: Deployment
metadata:
    name: httpd-frontend
    labels:
      app: httpd-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd-frontend
      app: httpd-frontend

  template:
    metadata:
      name: httpd-frontend
      labels:
        name: httpd-frontend
        app: httpd-frontend
    spec:
      containers:
      - name: httpd-frontend
        image: httpd:2.4-alpine
        ports:
          - containerPort: 80