apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
  name: webserver
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
  - name: sidecar-container
    image: ubuntu:latest
    command: ["/bin/sh", "-c", "while true; do (cat /var/log/nginx/access.log) && (cat /var/log/nginx/access.log); sleep 30; done"]
    # args: ["-c", "while true; do (cat /var/log/nginx/access.log) && (cat /var/log/nginx/access.log); sleep 30; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx

     
### Apply 
### kubectl apply -f pod-webserver.yml
### kubectl get po
### kubectl get po -o wide
### kubectl describe po