version: "3"
services: 
  apache: 
    image: httpd:latest
    container_name: httpd
    ports:
      - "6300:80"
    volumes: 
      - /opt/security:/usr/local/apache2/htdocs


# docker-compose up -d
# docker ps 
