version: '2'
services:
    web:
        build:
          context: "."
          dockerfile: Dockerfile
        container_name: python
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis
        container_name: redis