apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dep
  namespace: default
spec:
  replicas: 2
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 25%
  selector:
    matchLabels:
      app: hello-dep
  template:
    metadata:
      labels:
        app: hello-dep
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        imagePullPolicy: Always
        name: hello-dep
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /
             port: 8080
             initialDelaySeconds: 5
             periodSeconds: 5
             successThreshold: 1

######################

# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: nginx-test
# spec:
#   replicas: 10
#   selector:
#     matchLabels:
#       service: http-server
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 1
#   minReadySeconds: 5
#   template:
#     metadata:
#       labels:
#         service: http-server
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.10.2
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 80